import { mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'

import type { EndgeDomainBundle, GenerateResult } from './types.js'

interface EntityMeta {
  id: string
  identity: string
  name: string
}

interface GeneratedIdentitySpec {
  collectionKey: string
  generatedName: string
  baseTypeName: string
}

const GENERATED_IDENTITY_SPECS: GeneratedIdentitySpec[] = [
  { collectionKey: 'projects', generatedName: 'ProjectId', baseTypeName: 'EndgeProjectId' },
  { collectionKey: 'environments', generatedName: 'EnvId', baseTypeName: 'EndgeEnvId' },
  { collectionKey: 'tenants', generatedName: 'TenantId', baseTypeName: 'EndgeTenantId' },
  { collectionKey: 'folders', generatedName: 'FolderId', baseTypeName: 'EndgeFolderId' },
  { collectionKey: 'settings', generatedName: 'SettingsId', baseTypeName: 'EndgeSettingsId' },
  { collectionKey: 'types', generatedName: 'TypeId', baseTypeName: 'EndgeTypeId' },
  { collectionKey: 'queries', generatedName: 'QueryId', baseTypeName: 'EndgeQueryId' },
  { collectionKey: 'components', generatedName: 'ComponentId', baseTypeName: 'EndgeComponentId' },
  { collectionKey: 'scenarios', generatedName: 'ScenarioId', baseTypeName: 'EndgeScenarioId' },
  { collectionKey: 'actions', generatedName: 'ActionId', baseTypeName: 'EndgeActionId' },
  { collectionKey: 'converters', generatedName: 'ConverterId', baseTypeName: 'EndgeConverterId' },
  { collectionKey: 'integrations', generatedName: 'IntegrationId', baseTypeName: 'EndgeIntegrationId' },
  { collectionKey: 'views', generatedName: 'ViewId', baseTypeName: 'EndgeViewId' },
  { collectionKey: 'pageTemplates', generatedName: 'PageTemplateId', baseTypeName: 'EndgePageTemplateId' },
  { collectionKey: 'pages', generatedName: 'PageId', baseTypeName: 'EndgePageId' },
  { collectionKey: 'navigations', generatedName: 'NavigationId', baseTypeName: 'EndgeNavigationId' },
  { collectionKey: 'parameters', generatedName: 'ParameterId', baseTypeName: 'EndgeParameterId' },
  { collectionKey: 'filters', generatedName: 'FilterId', baseTypeName: 'EndgeFilterId' },
  { collectionKey: 'behaviorBindings', generatedName: 'BehaviorBindingId', baseTypeName: 'EndgeBehaviorBindingId' },
  { collectionKey: 'presentationBindings', generatedName: 'PresentationBindingId', baseTypeName: 'EndgePresentationBindingId' },
  { collectionKey: 'policies', generatedName: 'PolicyId', baseTypeName: 'EndgePolicyId' },
  { collectionKey: 'styles', generatedName: 'StyleId', baseTypeName: 'EndgeStyleId' },
  { collectionKey: 'vocabs', generatedName: 'VocabId', baseTypeName: 'EndgeVocabId' },
]

function stringifyJson(value: unknown): string {
  return `${JSON.stringify(value, null, 2)}\n`
}

function ensureObject(value: unknown): Record<string, unknown> {
  return value && typeof value === 'object' && !Array.isArray(value)
    ? value as Record<string, unknown>
    : {}
}

function ensureArray(value: unknown): Record<string, unknown>[] {
  return Array.isArray(value)
    ? value.filter(item => item && typeof item === 'object') as Record<string, unknown>[]
    : []
}

function toText(value: unknown, fallback: string): string {
  const text = typeof value === 'string' ? value.trim() : String(value ?? '').trim()
  return text || fallback
}

function toEntityMeta(items: unknown): EntityMeta[] {
  return ensureArray(items).map((item, index) => {
    const identity = toText(item.identity, `item_${index + 1}`)
    const idValue = item.id
    return {
      id: idValue == null ? identity : String(idValue),
      identity,
      name: toText(item.name ?? item.displayName, identity),
    }
  })
}

function createUniqueKeys(items: EntityMeta[]): Record<string, string> {
  const used = new Set<string>()
  const entries: Array<[string, string]> = []

  for (const item of items) {
    const base = item.identity
      .replace(/[^a-zA-Z0-9]+/g, '_')
      .replace(/^_+|_+$/g, '')
      .replace(/^\d/, '_$&')
      || 'item'

    let candidate = base
    let index = 2
    while (used.has(candidate)) {
      candidate = `${base}_${index}`
      index += 1
    }

    used.add(candidate)
    entries.push([candidate, item.identity])
  }

  return Object.fromEntries(entries)
}

function createIdentifiersSource(domain: Record<string, unknown>): string {
  const pages = createUniqueKeys(toEntityMeta(domain.pages))
  const views = createUniqueKeys(toEntityMeta(domain.views))
  const components = createUniqueKeys(toEntityMeta(domain.components))
  const queries = createUniqueKeys(toEntityMeta(domain.queries))
  const types = createUniqueKeys(toEntityMeta(domain.types))

  return `// Auto-generated by @endge/codegen. Do not edit manually.
export const generatedPageIds = ${JSON.stringify(pages, null, 2)} as const

export const generatedViewIds = ${JSON.stringify(views, null, 2)} as const

export const generatedComponentIds = ${JSON.stringify(components, null, 2)} as const

export const generatedQueryIds = ${JSON.stringify(queries, null, 2)} as const

export const generatedTypeIds = ${JSON.stringify(types, null, 2)} as const
`
}

function createMetaSource(bundle: EndgeDomainBundle): string {
  return `// Auto-generated by @endge/codegen. Do not edit manually.
export const generatedDomainMeta = ${JSON.stringify({
    version: bundle.version,
    exportedAt: bundle.exportedAt,
    sourceUrl: bundle.sourceUrl,
    projectId: bundle.projectId,
    environment: bundle.environment,
  }, null, 2)} as const
`
}

function createCatalogSource(): string {
  return `// Auto-generated by @endge/codegen. Do not edit manually.
import bundle from './domain.json'

export interface GeneratedEntityMeta {
  id: string
  identity: string
  name: string
}

export interface GeneratedDomainBundle {
  version: string
  exportedAt: string
  sourceUrl: string
  projectId: string | null
  environment: string | null
  domain: Record<string, unknown>
}

const domainBundle = bundle as GeneratedDomainBundle

function ensureArray(value: unknown): Record<string, unknown>[] {
  return Array.isArray(value)
    ? value.filter(item => item && typeof item === 'object') as Record<string, unknown>[]
    : []
}

function toText(value: unknown, fallback: string): string {
  const text = typeof value === 'string' ? value.trim() : String(value ?? '').trim()
  return text || fallback
}

function toEntityMeta(items: unknown): GeneratedEntityMeta[] {
  return ensureArray(items).map((item, index) => {
    const identity = toText(item.identity, \`item_\${index + 1}\`)
    const idValue = item.id
    return {
      id: idValue == null ? identity : String(idValue),
      identity,
      name: toText(item.name ?? item.displayName, identity),
    }
  })
}

function toLookup<T extends { identity: string }>(items: T[]): Record<string, T> {
  return Object.fromEntries(items.map(item => [item.identity, item]))
}

export const generatedDomainBundle = domainBundle
export const generatedDomain = domainBundle.domain

export const generatedPages = toEntityMeta(domainBundle.domain.pages)
export const generatedViews = toEntityMeta(domainBundle.domain.views)
export const generatedComponents = toEntityMeta(domainBundle.domain.components)
export const generatedQueries = toEntityMeta(domainBundle.domain.queries)
export const generatedTypes = toEntityMeta(domainBundle.domain.types)

export const generatedPagesByIdentity = toLookup(generatedPages)
export const generatedViewsByIdentity = toLookup(generatedViews)
export const generatedComponentsByIdentity = toLookup(generatedComponents)
export const generatedQueriesByIdentity = toLookup(generatedQueries)
export const generatedTypesByIdentity = toLookup(generatedTypes)

export function getGeneratedPage(identity: string): GeneratedEntityMeta | null {
  return generatedPagesByIdentity[identity] ?? null
}

export function getGeneratedView(identity: string): GeneratedEntityMeta | null {
  return generatedViewsByIdentity[identity] ?? null
}

export function getGeneratedComponent(identity: string): GeneratedEntityMeta | null {
  return generatedComponentsByIdentity[identity] ?? null
}

export function getGeneratedQuery(identity: string): GeneratedEntityMeta | null {
  return generatedQueriesByIdentity[identity] ?? null
}

export function getGeneratedType(identity: string): GeneratedEntityMeta | null {
  return generatedTypesByIdentity[identity] ?? null
}
`
}

function createIndexSource(): string {
  return `export * from './catalog'
export * from './domain.meta'
export * from './identifiers'
export * from './types'
`
}

function createGeneratedTypesSource(domain: Record<string, unknown>): string {
  const baseTypeImports = GENERATED_IDENTITY_SPECS
    .map(spec => spec.baseTypeName)
    .join(', ')

  const blocks = GENERATED_IDENTITY_SPECS.map((spec) => {
    const entries = createUniqueKeys(toEntityMeta(domain[spec.collectionKey]))
    const entryLiteral = JSON.stringify(entries, null, 2)
    const allName = `all${spec.generatedName}s`

    return `  export const ${spec.generatedName} = ${entryLiteral} as const
  export type ${spec.generatedName}
    = keyof typeof ${spec.generatedName} extends never
      ? ${spec.baseTypeName}
      : typeof ${spec.generatedName}[keyof typeof ${spec.generatedName}]
  export const ${allName} = Object.values(${spec.generatedName}) as ${spec.generatedName}[]
`
  }).join('\n')

  return `// Auto-generated by @endge/codegen. Do not edit manually.
import type { ${baseTypeImports} } from '@endge/core'

export namespace EndgeGen {
${blocks}}
`
}

export interface GenerateDomainArtifactsOptions {
  /** Папка, в которую писать сгенерированные файлы. По умолчанию: process.cwd()/src/gen */
  outputDir?: string
}

const DEFAULT_OUTPUT_DIR = path.join(process.cwd(), 'src', 'gen')

export async function generateDomainArtifacts(
  bundle: EndgeDomainBundle,
  options: GenerateDomainArtifactsOptions = {},
): Promise<GenerateResult> {
  const outputDir = path.resolve(options.outputDir ?? DEFAULT_OUTPUT_DIR)
  const domain = ensureObject(bundle.domain)

  await mkdir(outputDir, { recursive: true })

  const files = [
    { name: 'domain.json', contents: stringifyJson(bundle) },
    { name: 'domain.meta.ts', contents: createMetaSource(bundle) },
    { name: 'catalog.ts', contents: createCatalogSource() },
    { name: 'identifiers.ts', contents: createIdentifiersSource(domain) },
    { name: 'types.ts', contents: createGeneratedTypesSource(domain) },
    { name: 'index.ts', contents: createIndexSource() },
  ]

  await Promise.all(files.map(file =>
    writeFile(path.join(outputDir, file.name), file.contents, 'utf8'),
  ))

  return {
    outputDir,
    files: files.map(file => path.join(outputDir, file.name)),
  }
}
